name: coverage

on:
  push:
      branches:
        - main
      
jobs:
  upload-coverage:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.11
        uses: actions/setup-python@master
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install coverage orjson
      - name: Upload coverage
        run: |
          coverage run -m unittest discover
          coverage xml
          export CODACY_PROJECT_TOKEN=${{secrets.CODACY_PROJECT_TOKEN}}
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
