name: Tests

on:
  push:
    branches:    
      - main
      
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11']
        orjson: [true, false]

    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          if [ ${{ matrix.orjson }} == true" ]; then
            pip install -U orjson
          fi
      - name: Run unit tests
        run: |
          python run -m unittest discover
      - name: Report coverage
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
        run: |
          pip install coverage
          coverage run -m unittest discover
          coverage xml
          export CODACY_PROJECT_TOKEN=${{secrets.CODACY_PROJECT_TOKEN}}
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
